---
- name: Atelier Ansible - Séquence 5 (Multi-Environnement)
  hosts: all
  become: true
  gather_facts: true

  vars:
    # Variables communes
    prof_name: "Boris STOCKER"
    etudiant_name: "Jean-Gérard HOUNKANRIN"
    school_url: "https://www.epsi.fr/campus/paris"
    app_user: "{{ ansible_env.USER | default('Jean-Gérard') }}"
    page_dest: /var/www/html/index.html
    yarn_repo_file: /etc/apt/sources.list.d/yarn.list
    yarn_repo_disabled_file: /etc/apt/sources.list.d/yarn.list.disabled

  # Logique de bascule entre DEV et PROD
  pre_tasks:
    - name: "Configuration : Mode DEV"
      set_fact:
        page_title: "Application DEV"
        env_type: "dev"
        author: "Etudiant DEV"
        app_name: "Application DEV"
      # On vérifie que 'dev' est dans les groupes ET que l'on a limité à dev
      when: "'dev' in group_names"

    - name: "Configuration : Mode PROD"
      set_fact:
        page_title: "Application PROD"
        env_type: "prod"
        author: "Equipe Ops"
        app_name: "Application PROD"
      # On vérifie que 'prod' est dans les groupes ET que l'on a limité à prod
      when: "'prod' in group_names"

  tasks:
    - name: Remédiation dépôt Yarn
      block:
        - name: Vérifier si le dépôt Yarn existe
          stat:
            path: "{{ yarn_repo_file }}"
          register: yarn_repo_stat
        - name: Désactiver Yarn
          command: mv "{{ yarn_repo_file }}" "{{ yarn_repo_disabled_file }}"
          when: yarn_repo_stat.stat.exists
          changed_when: true

    - name: Installation de Nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Déployer la page dynamique
      template:
        src: files/index.html
        dest: "{{ page_dest }}"
        mode: "0644"
      notify: Redémarrer nginx

    - name: Assurer que Nginx est démarré
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Redémarrer nginx
      service:
        name: nginx
        state: restarted